#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

plugin-install() {
    local plugin_path="$PLUGIN_AVAILABLE_PATH/monit"

    if [[ ! -f "$DOKKU_ROOT/.monitrc" ]]; then
        cp monitrc "$DOKKU_ROOT/.monitrc"

        chown dokku:dokku "$DOKKU_ROOT/.monitrc"
        chmod 0500 "$DOKKU_ROOT/.monitrc"
    fi

    systemctl enable "$plugin_path/dokku-monit.service" --now
}

plugin-install
