#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

plugin-install() {
    cd $(dirname "$0")

    if [[ ! -f "$DOKKU_ROOT/.monitrc" ]]; then
        cp monitrc "$DOKKU_ROOT/.monitrc"

        chown dokku:dokku "$DOKKU_ROOT/.monitrc"
        chmod 0500 "$DOKKU_ROOT/.monitrc"
    fi

    if [[ ! -f /etc/systemd/system/dokku-monit.service ]]
        cp dokku-monit.service /etc/systemd/system/dokku-monit.service

        systemctl start dokku-monit
        systemctl enable dokku-monit
    fi
}

plugin-install
