#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/domains/functions"
source "$PLUGIN_AVAILABLE_PATH/certs/functions"

monit_build_config() {
    local dokku_bin="/usr/bin/dokku"
    local template_file="$plugin_path/templates/monit.sigil"
    local monit_config_file="$DOKKU_ROOT/$APP/monitrc"
    local domains=($(get_app_domains "$APP"))
    local domain="$(escape_domain ${domains[0]})"
    local address="localhost"

    local ssl=false
    local scheme="http"
    local port="$(escape_number "$(config_get "$APP" DOKKU_NGINX_PORT)")"

    if is_ssl_enabled "$APP"; then
        local ssl=true
        local scheme="https"
        local port="$(escape_number "$(config_get "$APP" DOKKU_NGINX_SSL_PORT)")"
    fi

    local content="$(escape_string "$(config_get "$APP" MONIT_CONTENT || true)")"
    local request="$(escape_string "$(config_get "$APP" MONIT_REQUEST || true)")"
    local alert="$(escape_string "$(config_get "$APP" MONIT_ALERT || true)")"
    local monit_enabled="$(config_get "$APP" MONIT_ENABLED || true)"

    sigil -f "$TEMPLATE_FILE" APP="$APP" DOMAIN="$domain" ALERT="$alert" CONTENT="$content" REQUEST="$request" PORT="$port" SCHEME="$scheme" SSL="$ssl" DOKKU_BIN="$dokku_bin" MONIT_ENABLED="$monit_enabled" ADDRESS="$address" > "$monit_config_file"

    monit reload
}

escape_string() {
    echo "${1//[^[:alnum:][:blank:]@.\/?=-]/}"
}

escape_domain() {
    echo "${1//[^[:alnum:].-]/}"
}

escape_number() {
    echo "${1//[^[:digit:]]/}"
}

monit_build_config
