#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/monit/functions"

monit_config_cmd() {
    local cmd="monit:config"
    # Support --app/$DOKKU_APP_NAME flag
    # Use the following lines to reorder args into "$cmd $DOKKU_APP_NAME $@""
    local argv=("$@")
    [[ ${argv[0]} == "$cmd" ]] && shift 1
    [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
    set -- $cmd $@
    ##

    [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
    local app="$2"; verify_app_name "$2"

    cat "$DOKKU_ROOT/$app/monitrc"
}

monit_config_cmd "$@"