#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/monit/functions"

log_cmd() {
    local args=""
    shift 1

    while getopts "f" option; do
        case $option in
            f ) local args="$args -f"
        esac
    done

    journalctl -u dokku-monit $args
}

log_cmd $@
