#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/monit/functions"

log_cmd() {
    local args=""
    shift 1

    local identifier_arg="-t monit"

    while getopts "fa" option; do
        case $option in
            f ) local args="$args -f"
                ;;
            a ) local identifier_arg=""
        esac
    done

    journalctl -u dokku-monit $identifier_arg $args
}

log_cmd $@
