#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/monit/functions"

monit_monitor_cmd() {
    local cmd="monit:monitor"
    # Support --app/$DOKKU_APP_NAME flag
    # Use the following lines to reorder args into "$cmd $DOKKU_APP_NAME $@""
    local argv=("$@")
    [[ ${argv[0]} == "$cmd" ]] && shift 1
    [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
    set -- $cmd $@
    ##

    [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
    local app="$2"; verify_app_name "$2"

    monit_cmd monitor "$app"
}

monit_monitor_cmd "$@"
